// client/pages/Login.tsx
import { useState } from "react";
import { Shield, Eye, EyeOff } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { AnimatedBackground } from "../components/AnimatedBackground";
import { Link, useNavigate } from "react-router-dom";

export default function Login() {
  const [emailId, setEmailId] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Handle login logic here
    console.log({ emailId, password });
    // For demo purposes, redirect to dashboard
    navigate("/");
  };

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Animated Background */}
      <AnimatedBackground />
      
      {/* Content */}
      <div className="relative z-10 min-h-screen flex items-center justify-center p-4">
        <div className="w-full max-w-6xl flex items-center justify-between">
          {/* Left Side - Logo and Text */}
          <div className="hidden lg:flex flex-col items-start space-y-4 text-white">
            <div className="flex items-center space-x-3">
              <div className="h-12 w-12 rounded-lg bg-dashboard-accent-blue flex items-center justify-center">
                <Shield className="h-7 w-7 text-white" />
              </div>
              <span className="text-4xl font-bold">SnapDrop</span>
            </div>
            <p className="text-xl text-blue-200 max-w-md">
              Lorem ipsum dolor sit
            </p>
          </div>

          {/* Right Side - Login Form */}
          <div className="w-full max-w-md">
            {/* Mobile Logo */}
            <div className="lg:hidden flex items-center justify-center space-x-3 mb-8">
              <div className="h-12 w-12 rounded-lg bg-dashboard-accent-blue flex items-center justify-center">
                <Shield className="h-7 w-7 text-white" />
              </div>
              <span className="text-4xl font-bold text-white">SnapDrop</span>
            </div>

            {/* Login Card */}
            <div className="bg-dashboard-card/90 backdrop-blur-sm border border-border/50 rounded-xl p-8 shadow-2xl">
              <h2 className="text-2xl font-bold text-foreground mb-6">Login</h2>
              
              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Email Field */}
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-sm font-medium text-foreground">
                    Email ID
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="Enter Email ID"
                    value={emailId}
                    onChange={(e) => setEmailId(e.target.value)}
                    className="bg-dashboard-bg/50 border-border/50 text-foreground placeholder:text-muted-foreground"
                    required
                  />
                </div>

                {/* Password Field */}
                <div className="space-y-2">
                  <Label htmlFor="password" className="text-sm font-medium text-foreground">
                    Password
                  </Label>
                  <div className="relative">
                    <Input
                      id="password"
                      type={showPassword ? "text" : "password"}
                      placeholder="Enter Password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="bg-dashboard-bg/50 border-border/50 text-foreground placeholder:text-muted-foreground pr-10"
                      required
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 hover:bg-transparent"
                      onClick={() => setShowPassword(!showPassword)}
                    >
                      {showPassword ? (
                        <EyeOff className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <Eye className="h-4 w-4 text-muted-foreground" />
                      )}
                    </Button>
                  </div>
                </div>

                {/* Forgot Password */}
                <div className="text-right">
                  <Link 
                    to="/forgot-password" 
                    className="text-sm text-dashboard-accent-blue hover:text-dashboard-accent-blue/80 transition-colors"
                  >
                    Forgot Password
                  </Link>
                </div>

                {/* Login Button */}
                <Button
                  type="submit"
                  className="w-full bg-dashboard-accent-blue hover:bg-dashboard-accent-blue/90 text-white font-medium py-2.5"
                >
                  LOGIN
                </Button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// snapdrop-angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatIconModule,
    MatButtonModule
  ],
  template: `
    <div class="login-page">
      <div class="login-background">
        <div class="background-lines"></div>
      </div>
      
      <div class="login-content">
        <div class="login-header">
          <div class="logo">
            <mat-icon class="logo-icon">security</mat-icon>
            <span class="logo-text">SnapDrop</span>
          </div>
          <p class="login-subtitle">Lorem ipsum dolor sit</p>
        </div>
        
        <div class="login-form-container">
          <form [formGroup]="loginForm" (ngSubmit)="onLogin()" class="login-form">
            <h2 class="form-title">Login</h2>
            
            <div class="form-group">
              <label class="form-label">Email ID</label>
              <input 
                type="email" 
                class="form-control"
                placeholder="Enter Email ID"
                formControlName="email"
              >
            </div>
            
            <div class="form-group">
              <label class="form-label">Password</label>
              <input 
                type="password" 
                class="form-control"
                placeholder="Enter Password"
                formControlName="password"
              >
            </div>
            
            <div class="form-actions">
              <a href="#" class="forgot-password">Forgot Password?</a>
              <button type="submit" class="btn btn-primary login-btn" [disabled]="!loginForm.valid">
                Login
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .login-page {
      height: 100vh;
      display: flex;
      position: relative;
      overflow: hidden;
    }
    
    .login-background {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: linear-gradient(135deg, #1e3a8a 0%, #1e40af 50%, #3b82f6 100%);
      
      .background-lines {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-image: 
          linear-gradient(45deg, rgba(255,255,255,0.1) 1px, transparent 1px),
          linear-gradient(-45deg, rgba(255,255,255,0.1) 1px, transparent 1px);
        background-size: 60px 60px;
        animation: moveLines 20s linear infinite;
      }
    }
    
    .login-content {
      position: relative;
      z-index: 2;
      width: 100%;
      display: flex;
      align-items: center;
      padding: 2rem;
      gap: 4rem;
    }
    
    .login-header {
      flex: 1;
      color: white;
      padding-left: 2rem;
      
      .logo {
        display: flex;
        align-items: center;
        gap: 1rem;
        margin-bottom: 1rem;
        
        .logo-icon {
          font-size: 2.5rem;
          background: rgba(255, 255, 255, 0.2);
          padding: 0.75rem;
          border-radius: 12px;
        }
        
        .logo-text {
          font-size: 2rem;
          font-weight: 700;
        }
      }
      
      .login-subtitle {
        font-size: 1.125rem;
        opacity: 0.9;
        margin: 0;
      }
    }
    
    .login-form-container {
      flex: 0 0 400px;
      
      .login-form {
        background: rgba(15, 23, 42, 0.9);
        backdrop-filter: blur(20px);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 16px;
        padding: 2rem;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3);
        
        .form-title {
          color: white;
          font-size: 1.5rem;
          font-weight: 600;
          margin-bottom: 2rem;
          text-align: center;
        }
        
        .form-group {
          margin-bottom: 1.5rem;
          
          .form-label {
            display: block;
            color: rgba(255, 255, 255, 0.9);
            font-size: 0.875rem;
            font-weight: 500;
            margin-bottom: 0.5rem;
          }
          
          .form-control {
            width: 100%;
            padding: 0.75rem;
            background: rgba(255, 255, 255, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
            border-radius: 8px;
            color: white;
            font-size: 0.875rem;
            transition: all 0.2s ease;
            
            &:focus {
              outline: none;
              border-color: #60a5fa;
              background: rgba(255, 255, 255, 0.15);
              box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.2);
            }
            
            &::placeholder {
              color: rgba(255, 255, 255, 0.6);
            }
          }
        }
        
        .form-actions {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 2rem;
          
          .forgot-password {
            color: rgba(255, 255, 255, 0.8);
            font-size: 0.875rem;
            text-decoration: none;
            transition: color 0.2s ease;
            
            &:hover {
              color: #60a5fa;
            }
          }
          
          .login-btn {
            background: #60a5fa;
            border: none;
            padding: 0.75rem 2rem;
            border-radius: 8px;
            font-weight: 500;
            transition: all 0.2s ease;
            
            &:hover:not(:disabled) {
              background: #3b82f6;
              transform: translateY(-1px);
            }
            
            &:disabled {
              opacity: 0.5;
              cursor: not-allowed;
            }
          }
        }
      }
    }
    
    @keyframes moveLines {
      0% {
        transform: translate(0, 0);
      }
      100% {
        transform: translate(60px, 60px);
      }
    }
    
    @media (max-width: 768px) {
      .login-content {
        flex-direction: column;
        justify-content: center;
        gap: 2rem;
        
        .login-header {
          text-align: center;
          padding-left: 0;
        }
        
        .login-form-container {
          flex: none;
          width: 100%;
          max-width: 400px;
        }
      }
    }
    
    @media (max-width: 480px) {
      .login-content {
        padding: 1rem;
      }
      
      .login-form-container .login-form {
        padding: 1.5rem;
      }
    }
  `]
})
export class LoginComponent {
  loginForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  onLogin() {
    if (this.loginForm.valid) {
      // Simulate login
      console.log('Login successful', this.loginForm.value);
      this.router.navigate(['/policies']);
    }
  }
}
